            - name: Actions Readme Feed
  # You may pin to the exact commit or the version.
  # uses: sarisia/actions-readme-feed@bdde7fdb36e19b030b77cf1f7b7f09db68219f32
  uses: sarisia/actions-readme-feed@v1.10.1
  with:
    # RSS Feed URL
    url: 
    # Path to Markdown file to update
    file: 
    # Sort feed entries by date in decending order
    sort: # optional, default is true
    # Number of entries to show
    max_entry: # optional, default is 5
    # Feed format string
    format: # optional, default is - ${monthshort} ${02day} - [${title}](${url})
    # Start of feed block in Markdown
    start_flag: # optional, default is <!-- feed start -->
    # End of feed block in Markdown
    end_flag: # optional, default is <!-- feed end -->
    # Locale used to format date
    locale: # optional, default is en-US
    # Timezone used to format date
    timezone: # optional, default is UTC
    # Do not write results to the file specified as `file` input
    nowrite: # optional, default is false
    # Number of retries for fetching feeds
    retry: # optional, default is 3
    # Retry backoff (seconds)
    retry_backoff: # optional, default is 5
    # Ensure that all feeds specified in url input are fetched correctly before proceed
    ensure_all: # optional, default is false
    # Don't fail action if feed has no items
    allow_empty: # optional, default is false
          
